aromableapp/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = "aromableapp"

urlpatterns = [
    path('', home, name='home'),
    path('home/', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('categories/', category_list, name='categories'),
    path('category/form', category_form, name='category_form'),
    path('categories/<int:category_id>', category_details, name='category'),
    path('categories/<int:category_id>/form', category_edit_form, name='category_edit_form'),



    path('recipes/', recipe_list, name='recipes'),
    path('recipe/form', recipe_form, name='recipe_form'),
    path('recipes/<int:recipe_id>', recipe_details, name='recipe'),
    path('recipes/<int:recipe_id>/form', recipe_edit_form, name='recipe_edit_form'),


    path('favorites/', favorite_list, name='favorites'),
    path('favorites/<int:recipe_id>/', favorite, name='favorite'),






    path('ingredients/', ingredient_list, name='ingredients'),
    path('ingredient/form', ingredient_form, name='ingredient_form'),
    path('ingredients/<int:ingredient_id>', ingredient_details, name='ingredient'),
    path('ingredients/<int:ingredient_id>/form', ingredient_edit_form, name='ingredient_edit_form'),

    url(r'^recipe-ingredients/$', recipeingredient_list, name='recipe_ingredients'),



    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^register/$', register_user, name='register'),
]

aromableproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from aromableapp.models import *


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('aromableapp.urls')),
]

aromableapp/models.py
from django.db import models

# Create your models here.

aromableapp/models/aromableuser.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save



class Aromableuser(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)


    class Meta:
        verbose_name = ("Aromableuser")
        verbose_name_plural = ("Aromableusers")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

@receiver(post_save, sender=User)
def create_aromableuser(sender, instance, created, **kwargs):
    if created:
        Aromableuser.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_aromableuser(sender, instance, **kwargs):
    instance.aromableuser.save()

aromableapp/models/category.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Category(models.Model):

    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = ("category")
        verbose_name_plural = ("categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"pk": self.pk})

aromableapp/models/favorite.py
from django.db import models
from .recipe import Recipe
from django.urls import reverse
from django.contrib.auth.models import User

class Favorite(models.Model):

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    

    class Meta:
            verbose_name = ("favorite")
            verbose_name_plural = ("favorites")

    def __str__(self):
        return self.recipe

    def get_absolute_url(self):
        return reverse("favorite_detail", kwargs={"pk": self.pk})

aromableapp/models/ingredient.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Ingredient(models.Model):

    name = models.CharField(max_length=50, blank=True, null=True)
    notes = models.CharField(max_length=150, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = ("ingredient")
        verbose_name_plural = ("ingredients")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ingredient_detail", kwargs={"pk": self.pk})

aromableapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

aromableapp/models/recipe.py
from django.db import models
from .category import Category
from django.urls import reverse
from django.contrib.auth.models import User

class Recipe(models.Model):

    name = models.CharField(max_length=50, blank=True, null=True)
    notes = models.CharField(max_length=150, blank=True, null=True)

    #foreign keys
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = ("recipe")
        verbose_name_plural = ("recipes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("recipe_detail", kwargs={"pk": self.pk})

aromableapp/models/recipeingredient.py
from django.db import models
from .recipe import Recipe
from .ingredient import Ingredient

class RecipeIngredient(models.Model):


    quantity = models.IntegerField(blank=True, null=True)

#foreign keys
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredient_list')
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)

aromableapp/views.py
from django.shortcuts import render

# Create your views here.

aromableapp/views/connection.py
class Connection:
    db_path = "/Users/kgallegos/workspace/python/aromable-backend/aromableproject/db.sqlite3"

aromableapp/views/home.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

aromableapp/templates/categories/detail.html
{% extends 'shared/base.html' %}

{% block content %}
    <section id="categories">
            <h5>Name: {{ category.name }}</h5>

    </section>


    <section id="category-actions" style="display:flex;">
        <form action="{% url 'aromableapp:category' category.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>

        <form action="{% url 'aromableapp:category_edit_form' category.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>
{% endblock %}

aromableapp/templates/categories/form.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/categoryform.css' %}"  />
{% endblock %}

{% block content %}

{% load static %}
<img src="{% static 'images/addcategories.png' %}" style="width:auto;height:150px;margin-bottom:30px;display:block;
margin-left: auto;
margin-right: auto;"  >


    <!-- <h1>Enter a category</h1> -->

    {% if category.id is not None %}
        <form action="{% url 'aromableapp:category' category.id %}" method="post">
    {% else %}
        <form action="{% url 'aromableapp:categories' %}" method="post">
    {% endif %}
        {% csrf_token %}

        <div class="form-group insideformdiv">
        <fieldset>
            <label for="name"> </label>
            <input class ="form-control" id="name" type="text" name="name" placeholder="Enter Name of Category" value="{{ category.name }}">
        </fieldset>
        <!-- <fieldset>
            <label for="notes">Notes:</label>
            <input id="notes" type="text" name="notes" value="{{ category.notes }}">
        </fieldset> -->
        <div class="buttonoil2">
        {% if category.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input class="ingredientoil buttonoil"  type="submit" value="Update" />
        {% else %}
            <input class="ingredientoil buttonoil"  type="submit" value="Save" />
        {% endif %}
</div>
    </form>

{% endblock %}

aromableapp/templates/categories/list.html
{% extends 'shared/base.html' %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/categorylist.css' %}"  />
{% endblock %}

{% block content %}

{% load static %}
<img src="{% static 'images/categorylist.png' %}"
style="width:auto;
height:150px;
margin-left: auto;
margin-right: auto;
margin-top: 20px;
display: block;"  >

<br>
<div class = "addoildiv main-content">
<div class="addcategory">
    <a class="addcategorytext" href="{% url 'aromableapp:category_form' %}">Add Category</a>
</div>



    <ol>
    {% for category in all_categories %}
        <li class="oillistdesign">
            <a class="categoryname">
            <!-- <a class="categoryname" href="{% url 'aromableapp:category' category.id %}"> -->

                {{ category.name }}
            </a>
            <!-- ({{ category.notes }}) -->
            <ul>


            </ul>


            <section id="category-actions" >

                    <form action="{% url 'aromableapp:category' category.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="actual_method" value="DELETE">
                        <button class="btn btn-secondary category">Delete</button>
                    </form>

                    <form action="{% url 'aromableapp:category_edit_form' category.id %}" method="GET">
                        {% csrf_token %}
                        <button class="btn btn-secondary category" >Edit</button>
                    </form>
                </section>


                </li>

    {% endfor %}
</ol>
</div>
{% endblock %}

aromableapp/templates/favorites/detail.html
{% comment %} {% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>My Favorite Recipes</title>
</head>

<body>

    <section id="favorite-details">
        <h1>Favorite Recipes: {{ recipe.name }}</h1>
        <h1>Recipe Name: </h1>
        <ol>
        {% for recipe in category.recipes.all %}
            <li>
                <a href="{% url 'aromableapp:recipe' recipe.id %}"> {{ recipe.name }}</a>
            </li>
        {% endfor %}
        </ol>

    </section>

</body>
</html> {% endcomment %}

aromableapp/templates/favorites/list.html
{% extends 'shared/base.html' %}


{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/favoritelist.css' %}"  />
{% endblock %}


{% block content %}

{% load static %}
<img class="favorites" src="{% static 'images/favorites.png' %}"
style="width:auto;
height:130px;
margin-left: auto;
margin-right: auto;
margin-top: 20px;
display: block;"  >
<br>

    <!-- <h1>Favorites</h1> -->
<div class="favoritediv" >
    <ul >
    {% for favorite in all_favorites %}

      <a class="favoritelist" href="{% url 'aromableapp:recipe' favorite.recipe_id %}">{{favorite.recipe.name }}</a> <br>

    {% endfor %}
    </ul>
  </div>

  </body>
</html>
{% endblock content%}

aromableapp/templates/home.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/home.css' %}" class="homeimage" />
{% endblock %}

{% block content %}

{% load static %}
<img src="{% static 'images/aromablelogo.png' %}" style="width:auto;height:300px;margin-bottom:30px;display:block;
margin-left: auto;
margin-right: auto;"  >


<h3> Hi {{ user.first_name }}!</h3> <br>

<div class="homebuttons allbuttons">
<a class="btn btn-secondary home space" href="{% url 'aromableapp:ingredient_form' %}">Add Oil</a>
<a class="btn btn-secondary home space" href="{% url 'aromableapp:ingredients' %}">View Oil Inventory</a>
<a class="btn btn-secondary home space" href="{% url 'aromableapp:category_form' %}">Add Category</a>
<a class="btn btn-secondary home space" href="{% url 'aromableapp:recipes' %}">View Oil Blends</a>
<a class="btn btn-secondary home space" href="{% url 'aromableapp:recipe_form' %}">Add Oil Blend</a>
<a class="btn btn-secondary home space" href="{% url 'aromableapp:favorites' %}">View My Favorites</a>

{% endblock content %}
</div>

ß

aromableapp/templates/ingredients/detail.html
{% extends 'shared/base.html' %}

{% block content %}
    <section id="ingredients">
            <h5>Name: {{ ingredient.name }}</h5>
            <h6>Notes: {{ ingredient.notes }}</h6>

    </section>


    <section id="ingredient-actions" style="display:flex;">
        <form action="{% url 'aromableapp:ingredient' ingredient.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>

        <form action="{% url 'aromableapp:ingredient_edit_form' ingredient.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>
{% endblock %}

aromableapp/templates/ingredients/form.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/ingredientform.css' %}"  />
{% endblock %}

{% block content %}

{% load static %}
<img src="{% static 'images/AddOil.png' %}" style="width:auto;height:150px;margin-bottom:30px;display:block;
margin-left: auto;
margin-right: auto;"  >

    <!-- <h1 class="enteroil">Enter Your Oil</h1> -->

    {% if ingredient.id is not None %}
        <form action="{% url 'aromableapp:ingredient' ingredient.id %}" method="post">
    {% else %}
        <form action="{% url 'aromableapp:ingredients' %}" method="post">
    {% endif %}
        {% csrf_token %}



        <div class="form-group insideformdiv">
        <fieldset>

            <label for="name"> </label>
            <input class="form-control" id="name" type="text" name="name" placeholder="Oil Name" value="{{ ingredient.name }}">
        </fieldset>
        <fieldset>
            <label for="notes"> </label>
            <input class="form-control" id="notes" type="text" name="notes" placeholder="Oil Notes" value="{{ ingredient.notes }}">
        </fieldset>


<div class="buttonoil2">
        {% if ingredient.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" class="ingredientoil buttonoil"/>
        {% else %}
            <input type="submit" value="Save" class="ingredientoil buttonoil" />
        {% endif %}
    </div>
</div>


{% endblock %}

aromableapp/templates/ingredients/list.html
{% extends 'shared/base.html' %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/ingredientlist.css' %}"  />
{% endblock %}


{% block content %}

{% load static %}
<img src="{% static 'images/oillist.png' %}"
style="width:auto;
height:150px;
margin-left: auto;
margin-right: auto;
margin-top: 20px;
display: block;"  >

<br>
<div class = "addoildiv main-content">
<div class="addoil ">
    <a class="addoiltext" href="{% url 'aromableapp:ingredient_form' %}">Add Oil</a>
</div>


    <ol>
    {% for ingredient in all_ingredients %}
        <li class="oillistdesign">
            <!-- <a class="oilname" href="{% url 'aromableapp:ingredient' ingredient.id %}"> -->
            <a class="oilname" >

                {{ ingredient.name }}
            </a>
            <!-- ({{ ingredient.notes }}) -->
            <ul>

                <li class="oilnotes">{{ ingredient.notes }}</li>

            </ul>
            <div class="pleasework">
            <section id="ingredient-actions" style="display:flex;">
                    <form class="ingredient-actions2" action="{% url 'aromableapp:ingredient' ingredient.id %}" method="POST">
                        {% csrf_token %}
                        <input  type="hidden" name="actual_method" value="DELETE">
                        <button class="btn btn-secondary oil buttons" >Delete</button>
                    </form>

                    <form action="{% url 'aromableapp:ingredient_edit_form' ingredient.id %}" method="GET">
                        {% csrf_token %}
                        <button  class="btn btn-secondary oil buttons" >Edit</button>
                    </form>
                </section>
            </div>
        </li>
    {% endfor %}
    </ol>
</div>

{% endblock %}

aromableapp/templates/recipes/detail.html
{% extends 'shared/base.html' %} {% load staticfiles %} {% block css %}
<link rel="stylesheet" href="{% static 'styles/recipedetail.css' %}" />
{% endblock %} {% block content %} {% load static %}
<img
  src="{% static 'images/recipedetails.png' %}"
  style="width:auto;
height:150px;
margin-bottom:30px;
margin-left: auto;
margin-right: auto;"
/>
<!-- <h1>{{favorited}}</h1> -->
<section id="recipe-details">
  <p>Name: {{ recipe.name }}</p>
  <p>Notes: {{ recipe.notes }}</p>
  <p>Category: {{ recipe.category.name }}</p>


  <div class="oilnamesdiv">
    Oil(s): {% for relationship in recipe.ingredient_list.all %}
    {{ relationship.ingredient.name }} |
    {% endfor %}
  </div>
</section>

<section id="recipe-actions" style="display:flex;">
  <form action="{% url 'aromableapp:favorite' recipe.id  %}" method="POST">
    {% csrf_token %}

    {% if favorited is False%}
    <input type="hidden" name="actual_method" value="DELETE" />
    <button class="btn btn-secondary redetail">Remove from Favorites</button>
  </form>

  {% else %}
  <form action="{% url 'aromableapp:favorites' %}" method="DELETE">
    {% csrf_token %}

    <input
      type="hidden"
      name="recipe_id"
      id="recipe_id"
      value="{{ recipe.id }}"
    />
    <button
      class="btn btn-secondary redetail"
      value="{{ recipe.id }}"
      type="submit"
    >
      Add To Favorites
    </button>
    {% endif %}
  </form>

  <form action="{% url 'aromableapp:recipe' recipe.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="actual_method" value="DELETE" />
    <button class="btn btn-secondary redetail">Delete Recipe</button>
  </form>

  <form
    action="{% url 'aromableapp:recipe_edit_form' recipe.id %}"
    method="GET"
  >
    {% csrf_token %}
    <button class="btn btn-secondary redetail">Edit Recipe</button>
  </form>
</section>
{% endblock %}

aromableapp/templates/recipes/form.html
{% extends 'shared/base.html' %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/recipeform.css' %}"  />
{% endblock %}

{% block content %}

{% load static %}
<img src="{% static 'images/addrecipe.png' %}" style="width:auto;height:150px;margin-bottom:30px;display:block;
margin-left: auto;
margin-right: auto;"  >




{% if recipe.id is not None %}
<form action="{% url 'aromableapp:recipe' recipe.id %}" method="post">
  {% else %}
  <form action="{% url 'aromableapp:recipes' %}" method="post">
    {% endif %}
    {% csrf_token %}


    <div class="form-group insideformdiv">
    <fieldset>
      <label for="name"> </label>
      <input class="form-control" id="name" type="text" name="name" placeholder="Oil Blend Name" value="{{ recipe.name }}" />
    </fieldset>
    <fieldset>
      <label for="notes"></label>
      <input class="form-control" id="notes" type="text" name="notes" placeholder="Oil Blend Notes" value="{{ recipe.notes }}" />
    </fieldset>
    <fieldset>
      <label for="exampleSelect1 category">Category </label>
      <select class="form-control recipedropdown" id="exampleSelect1 category" type="text" name="category">

        {% for category in all_categories%}
        <option value="{{ category.id }}"> {{ category.name }}</option>
        {% endfor %}
      </select>
    </fieldset>

    <fieldset>
      <label class="oilscheckboxlabel" for="ingredient">Oils: </label>

      {% for ingredient in all_ingredients%}
      <input

      {% if ingredient.id in recipeingredients %}
        type="checkbox" checked
        id="ingredient{{ ingredient.id }}"
        name="ingredient[]"
        value="{{ ingredient.id }}"
      />
      {% else %}
      <input
        type="checkbox"
        id="ingredient{{ ingredient.id }}"
        name="ingredient[]"
        value="{{ ingredient.id }}"
      />

      {% endif %}
      {{ ingredient.name }}
      {% endfor %}

    </fieldset>


    <div class="buttonoil2">

    {% if recipe.id is not None %}
    <input type="hidden" name="actual_method" value="PUT" />
    <input type="submit" value="Update" class="ingredientoil" />
    {% else %}
    <input type="submit" value="Add Oil Blend" class="ingredientoil" />
    {% endif %}
  </form>

  {% endblock %}
</div>
</div>
</form>

aromableapp/templates/recipes/list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/recipelist.css' %}"  />
{% endblock %}

{% block content %}

{% load static %}
<img src="{% static 'images/recipelist.png' %}"
style="width:auto;
height:95px;
margin-bottom:10px;
margin-left: auto;
margin-right: auto;"  >



    <!-- <h1>Recipes</h1> -->
<br>
<div class="addrecipediv"></div>
    <a class="addrecipe" href="{% url 'aromableapp:recipe_form' %}">Add Oil Blend</a>

    <ol>
    {% for recipe in all_recipes %}

        <li >
            <a class="recipename" href="{% url 'aromableapp:recipe' recipe.id %}">{{ recipe.name }}</a>
            <br><ul class="catnotes" >Category: {{ recipe.category.name }}</ul>  <br>
        </li>

    {% endfor %}


    <!-- <div><a href="{% url 'aromableapp:home' %}">Go Back</a></div> -->
    </ol>

{% endblock %}

aromableapp/templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Aromable nav bar list.py</title>

    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- <style>
        .navList {
            list-style-type: none;
            display: flex;
            border: 1px solid lightgray;
            padding: 1em;
        }
         .navList__route {
                margin: 0 0.5em;
         }
    </style> -->

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />

    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route navbarspace"><a class="links" href="{% url 'aromableapp:home' %}">Home</a></li>
            <li class="navList__route navbarspace"><a class="links" href="{% url 'aromableapp:ingredients' %}">Oils</a></li>
            <li class="navList__route navbarspace"><a class="links" href="{% url 'aromableapp:categories' %}">Categories</a></li>
            <li class="navList__route navbarspace"><a class="links" href="{% url 'aromableapp:recipes' %}">Oil Blends</a></li>

            <li class="navList__route navbarspace"><a class="links" href="{% url 'aromableapp:favorites' %}">Favorites</a></li>
            <li class="navList__route navbarspace"><a class="links" href="{% url 'aromableapp:logout' %}">Logout</a></li>
            <li class="navList__route navbarspace"><a class="links" href="{% url 'aromableapp:register' %}">Register</a></li>
            <img src="{% static 'images/aromablesmlogo.png' %}"
            style="width:auto;
            height:60px; margin-left: auto;"  >
        </ol>


    </nav>

    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock %}
</body>

</html>